SeabreezeShipping_MapScripts::
	.byte 0

SeabreezeShipping_EventScript_Receptionist1::
	msgbox SeabreezeShipping_Text_Receptionist1_1, MSGBOX_NPC
	end

SeabreezeShipping_Text_Receptionist1_1:
	.string "Welcome to Seabreeze Shipping HQ!\p"
	.string "We apologize, but we are\n"
	.string "closed for the time being.$"

SeabreezeShipping_EventScript_Elevatorman::
	msgbox SeabreezeShipping_Text_Elevatorman_1, MSGBOX_NPC
	end

SeabreezeShipping_Text_Elevatorman_1:
	.string "Sorry, kid. We're closed.$"

