RustboroCity_House2_MapScripts::
	.byte 0

RustboroCity_House2_EventScript_PokefanF::
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end

RustboroCity_House2_EventScript_LittleGirl::
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end

RustboroCity_House2_Text_TrainerSchoolExcellent:
	.string "Have you seen my husband, Gregor?\n"
	.string "He left for work days ago…\p"
	.string "He was a traveling salesman, always\n"
	.string "on the road. But he always came home.\p"
	.string "Something… something must have\n"
	.string "happened to him.$"

RustboroCity_House2_Text_RoxanneKnowsALot:
	.string "Mom's worried sick about Dad…\p"
	.string "I keep telling her, maybe he just\n"
	.string "…changed? Into something else?\p"
	.string "Ever since that strange comet passed\n"
	.string "through the sky… weird things happen.\p"
	.string "I heard strange clicking noises\n"
	.string "upstairs last night… It's terrifying.$"

