# 1 "data/maps/RustboroCity_House2/scripts.pory"

# 2 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_MapScripts::
# 3 "data/maps/RustboroCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/RustboroCity_House2/scripts.pory"

# 5 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_EventScript_PokefanF::
# 6 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
# 7 "data/maps/RustboroCity_House2/scripts.pory"
	end
# 8 "data/maps/RustboroCity_House2/scripts.pory"

# 9 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_EventScript_LittleGirl::
# 10 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
# 11 "data/maps/RustboroCity_House2/scripts.pory"
	end
# 12 "data/maps/RustboroCity_House2/scripts.pory"

# 13 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_TrainerSchoolExcellent:
# 14 "data/maps/RustboroCity_House2/scripts.pory"
	.string "Have you seen my husband, Gregor?\n"
# 15 "data/maps/RustboroCity_House2/scripts.pory"
	.string "He left for work days ago…\p"
# 16 "data/maps/RustboroCity_House2/scripts.pory"
	.string "He was a traveling salesman, always\n"
# 17 "data/maps/RustboroCity_House2/scripts.pory"
	.string "on the road, but he always came home.\p"
# 18 "data/maps/RustboroCity_House2/scripts.pory"
	.string "Something… something must have\n"
# 19 "data/maps/RustboroCity_House2/scripts.pory"
	.string "happened to him.$"
# 20 "data/maps/RustboroCity_House2/scripts.pory"

# 21 "data/maps/RustboroCity_House2/scripts.pory"
RustboroCity_House2_Text_RoxanneKnowsALot:
# 22 "data/maps/RustboroCity_House2/scripts.pory"
	.string "Mom's worried sick about Dad…\p"
# 23 "data/maps/RustboroCity_House2/scripts.pory"
	.string "I keep telling her, maybe he just\n"
# 24 "data/maps/RustboroCity_House2/scripts.pory"
	.string "…changed? Into something else?\p"
# 25 "data/maps/RustboroCity_House2/scripts.pory"
	.string "Ever since that strange comet passed\n"
# 26 "data/maps/RustboroCity_House2/scripts.pory"
	.string "through the sky… weird things happen.\p"
# 27 "data/maps/RustboroCity_House2/scripts.pory"
	.string "I heard strange clicking noises\n"
# 28 "data/maps/RustboroCity_House2/scripts.pory"
	.string "upstairs last night… It's terrifying.$"
