#ifndef GUARD_CONSTANTS_ACHIEVEMENTS_H
#define GUARD_CONSTANTS_ACHIEVEMENTS_H

#define ACHIEVEMENTS_MAX 128
#define ACHIEVEMENT_UNLOCKED_BYTES ((ACHIEVEMENTS_MAX + 7) / 8)
#define ACHIEVEMENT_POPUP_QUEUE_SIZE 6
#define ACHIEVEMENT_SAVE_MAGIC 0xACE1
#define ACHIEVEMENT_SAVE_DATA_SIZE 48

enum AchievementTier
{
    ACH_TIER_BRONZE,
    ACH_TIER_SILVER,
    ACH_TIER_GOLD,
    ACH_TIER_PLATINUM,
};

enum AchievementCounter
{
    ACH_COUNTER_CRITICAL_HITS,
    ACH_COUNTER_CAPTURED_MONS,
    ACH_COUNTER_SHINY_CAPTURES,
    ACH_COUNTER_DAYCARE_EGGS,
    ACH_COUNTER_HATCHED_EGGS,
    ACH_COUNTER_COUNT,
    ACH_COUNTER_EVOLVED_POKEMON = 0xF6,
    ACH_COUNTER_TMS_COLLECTED = 0xFD,
    ACH_COUNTER_POKEDEX_CAUGHT = 0xFE,
    ACH_COUNTER_NONE = 0xFF,
};

enum AchievementId
{
    ACH_RECEIVE_STARTER,
    ACH_FIRST_CAPTURE,
    ACH_FIRST_CRITICAL,
    ACH_CRITICAL_100,
    ACH_CAPTURE_100,
    ACH_CAPTURE_SHINY,
    ACH_DAYCARE_EGG_1,
    ACH_DAYCARE_EGGS_100,
    ACH_HATCH_EGGS_100,
    ACH_TM_1,
    ACH_TM_20,
    ACH_TM_50,
    ACH_TM_100,
    ACH_POKEDEX_200,
    ACH_POKEDEX_350,
    ACH_POKEDEX_500,
    ACH_PEAK_OF_POWER,
    ACH_GAINING_POWER,
    ACH_ID_COUNT,
};

#define ACH_LEGACY_ID_COUNT 0
#define ACH_COUNT ACH_ID_COUNT

#endif // GUARD_CONSTANTS_ACHIEVEMENTS_H
