#ifndef GUARD_CONSTANTS_ENCOUNTER_IDS_H
#define GUARD_CONSTANTS_ENCOUNTER_IDS_H

#define ENCOUNTER_ID_NONE 0xFFFF
#define ENCOUNTER_ID_CAPACITY 512

// Permanent 0.9 encounter identities. Never renumber/reuse an ID. New maps
// receive a fresh ID; their position in wild_encounters.json is irrelevant.
// Time-of-day tables share one identity; Altering Cave's nine sets stay separate.
// F(name, persistent ID, map, variant)
#define HLW_ENCOUNTER_REGISTRY(F) \
    F(ROUTE101, 0, MAP_ROUTE101, 0) \
    F(ROUTE102, 1, MAP_ROUTE102, 0) \
    F(ROUTE103, 2, MAP_ROUTE103, 0) \
    F(ROUTE104, 3, MAP_ROUTE104, 0) \
    F(ROUTE105, 4, MAP_ROUTE105, 0) \
    F(ROUTE110, 5, MAP_ROUTE110, 0) \
    F(ROUTE111, 6, MAP_ROUTE111, 0) \
    F(ROUTE112, 7, MAP_ROUTE112, 0) \
    F(ROUTE113, 8, MAP_ROUTE113, 0) \
    F(ROUTE114, 9, MAP_ROUTE114, 0) \
    F(ROUTE116, 10, MAP_ROUTE116, 0) \
    F(ROUTE117, 11, MAP_ROUTE117, 0) \
    F(ROUTE118, 12, MAP_ROUTE118, 0) \
    F(ROUTE124, 13, MAP_ROUTE124, 0) \
    F(PETALBURG_WOODS, 14, MAP_PETALBURG_WOODS, 0) \
    F(RUSTURF_TUNNEL, 15, MAP_RUSTURF_TUNNEL, 0) \
    F(GRANITE_CAVE_1F, 16, MAP_GRANITE_CAVE_1F, 0) \
    F(GRANITE_CAVE_B1F, 17, MAP_GRANITE_CAVE_B1F, 0) \
    F(MT_PYRE_1F, 18, MAP_MT_PYRE_1F, 0) \
    F(VICTORY_ROAD_1F, 19, MAP_VICTORY_ROAD_1F, 0) \
    F(SAFARI_ZONE_SOUTH, 20, MAP_SAFARI_ZONE_SOUTH, 0) \
    F(UNDERWATER_ROUTE126, 21, MAP_UNDERWATER_ROUTE126, 0) \
    F(ABANDONED_SHIP_ROOMS_B1F, 22, MAP_ABANDONED_SHIP_ROOMS_B1F, 0) \
    F(GRANITE_CAVE_B2F, 23, MAP_GRANITE_CAVE_B2F, 0) \
    F(FIERY_PATH, 24, MAP_FIERY_PATH, 0) \
    F(METEOR_FALLS_B1F_2R, 25, MAP_METEOR_FALLS_B1F_2R, 0) \
    F(JAGGED_PASS, 26, MAP_JAGGED_PASS, 0) \
    F(ROUTE106, 27, MAP_ROUTE106, 0) \
    F(ROUTE107, 28, MAP_ROUTE107, 0) \
    F(ROUTE108, 29, MAP_ROUTE108, 0) \
    F(ROUTE109, 30, MAP_ROUTE109, 0) \
    F(ROUTE115, 31, MAP_ROUTE115, 0) \
    F(NEW_MAUVILLE_INSIDE, 32, MAP_NEW_MAUVILLE_INSIDE, 0) \
    F(ROUTE119, 33, MAP_ROUTE119, 0) \
    F(ROUTE120, 34, MAP_ROUTE120, 0) \
    F(ROUTE121, 35, MAP_ROUTE121, 0) \
    F(ROUTE122, 36, MAP_ROUTE122, 0) \
    F(ROUTE123, 37, MAP_ROUTE123, 0) \
    F(MT_PYRE_2F, 38, MAP_MT_PYRE_2F, 0) \
    F(MT_PYRE_3F, 39, MAP_MT_PYRE_3F, 0) \
    F(MT_PYRE_4F, 40, MAP_MT_PYRE_4F, 0) \
    F(MT_PYRE_5F, 41, MAP_MT_PYRE_5F, 0) \
    F(MT_PYRE_6F, 42, MAP_MT_PYRE_6F, 0) \
    F(MT_PYRE_EXTERIOR, 43, MAP_MT_PYRE_EXTERIOR, 0) \
    F(MT_PYRE_SUMMIT, 44, MAP_MT_PYRE_SUMMIT, 0) \
    F(GRANITE_CAVE_STEVENS_ROOM, 45, MAP_GRANITE_CAVE_STEVENS_ROOM, 0) \
    F(ROUTE125, 46, MAP_ROUTE125, 0) \
    F(ROUTE126, 47, MAP_ROUTE126, 0) \
    F(ROUTE127, 48, MAP_ROUTE127, 0) \
    F(ROUTE128, 49, MAP_ROUTE128, 0) \
    F(ROUTE129, 50, MAP_ROUTE129, 0) \
    F(ROUTE130, 51, MAP_ROUTE130, 0) \
    F(ROUTE131, 52, MAP_ROUTE131, 0) \
    F(ROUTE132, 53, MAP_ROUTE132, 0) \
    F(ROUTE133, 54, MAP_ROUTE133, 0) \
    F(ROUTE134, 55, MAP_ROUTE134, 0) \
    F(ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS, 56, MAP_ABANDONED_SHIP_HIDDEN_FLOOR_CORRIDORS, 0) \
    F(SEAFLOOR_CAVERN_ROOM1, 57, MAP_SEAFLOOR_CAVERN_ROOM1, 0) \
    F(SEAFLOOR_CAVERN_ROOM2, 58, MAP_SEAFLOOR_CAVERN_ROOM2, 0) \
    F(SEAFLOOR_CAVERN_ROOM3, 59, MAP_SEAFLOOR_CAVERN_ROOM3, 0) \
    F(SEAFLOOR_CAVERN_ROOM4, 60, MAP_SEAFLOOR_CAVERN_ROOM4, 0) \
    F(SEAFLOOR_CAVERN_ROOM5, 61, MAP_SEAFLOOR_CAVERN_ROOM5, 0) \
    F(SEAFLOOR_CAVERN_ROOM6, 62, MAP_SEAFLOOR_CAVERN_ROOM6, 0) \
    F(SEAFLOOR_CAVERN_ROOM7, 63, MAP_SEAFLOOR_CAVERN_ROOM7, 0) \
    F(SEAFLOOR_CAVERN_ROOM8, 64, MAP_SEAFLOOR_CAVERN_ROOM8, 0) \
    F(SEAFLOOR_CAVERN_ENTRANCE, 65, MAP_SEAFLOOR_CAVERN_ENTRANCE, 0) \
    F(CAVE_OF_ORIGIN_ENTRANCE, 66, MAP_CAVE_OF_ORIGIN_ENTRANCE, 0) \
    F(CAVE_OF_ORIGIN_1F, 67, MAP_CAVE_OF_ORIGIN_1F, 0) \
    F(CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1, 68, MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP1, 0) \
    F(CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2, 69, MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP2, 0) \
    F(CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3, 70, MAP_CAVE_OF_ORIGIN_UNUSED_RUBY_SAPPHIRE_MAP3, 0) \
    F(NEW_MAUVILLE_ENTRANCE, 71, MAP_NEW_MAUVILLE_ENTRANCE, 0) \
    F(SAFARI_ZONE_SOUTHWEST, 72, MAP_SAFARI_ZONE_SOUTHWEST, 0) \
    F(SAFARI_ZONE_NORTH, 73, MAP_SAFARI_ZONE_NORTH, 0) \
    F(SAFARI_ZONE_NORTHWEST, 74, MAP_SAFARI_ZONE_NORTHWEST, 0) \
    F(VICTORY_ROAD_B1F, 75, MAP_VICTORY_ROAD_B1F, 0) \
    F(VICTORY_ROAD_B2F, 76, MAP_VICTORY_ROAD_B2F, 0) \
    F(METEOR_FALLS_1F_1R, 77, MAP_METEOR_FALLS_1F_1R, 0) \
    F(METEOR_FALLS_1F_2R, 78, MAP_METEOR_FALLS_1F_2R, 0) \
    F(METEOR_FALLS_B1F_1R, 79, MAP_METEOR_FALLS_B1F_1R, 0) \
    F(SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM, 80, MAP_SHOAL_CAVE_LOW_TIDE_STAIRS_ROOM, 0) \
    F(SHOAL_CAVE_LOW_TIDE_LOWER_ROOM, 81, MAP_SHOAL_CAVE_LOW_TIDE_LOWER_ROOM, 0) \
    F(SHOAL_CAVE_LOW_TIDE_INNER_ROOM, 82, MAP_SHOAL_CAVE_LOW_TIDE_INNER_ROOM, 0) \
    F(SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM, 83, MAP_SHOAL_CAVE_LOW_TIDE_ENTRANCE_ROOM, 0) \
    F(LILYCOVE_CITY, 84, MAP_LILYCOVE_CITY, 0) \
    F(DEWFORD_TOWN, 85, MAP_DEWFORD_TOWN, 0) \
    F(SLATEPORT_CITY, 86, MAP_SLATEPORT_CITY, 0) \
    F(MOSSDEEP_CITY, 87, MAP_MOSSDEEP_CITY, 0) \
    F(PACIFIDLOG_TOWN, 88, MAP_PACIFIDLOG_TOWN, 0) \
    F(EVER_GRANDE_CITY, 89, MAP_EVER_GRANDE_CITY, 0) \
    F(PETALBURG_CITY, 90, MAP_PETALBURG_CITY, 0) \
    F(UNDERWATER_ROUTE124, 91, MAP_UNDERWATER_ROUTE124, 0) \
    F(SHOAL_CAVE_LOW_TIDE_ICE_ROOM, 92, MAP_SHOAL_CAVE_LOW_TIDE_ICE_ROOM, 0) \
    F(SKY_PILLAR_1F, 93, MAP_SKY_PILLAR_1F, 0) \
    F(SOOTOPOLIS_CITY, 94, MAP_SOOTOPOLIS_CITY, 0) \
    F(SKY_PILLAR_3F, 95, MAP_SKY_PILLAR_3F, 0) \
    F(SKY_PILLAR_5F, 96, MAP_SKY_PILLAR_5F, 0) \
    F(SAFARI_ZONE_SOUTHEAST, 97, MAP_SAFARI_ZONE_SOUTHEAST, 0) \
    F(SAFARI_ZONE_NORTHEAST, 98, MAP_SAFARI_ZONE_NORTHEAST, 0) \
    F(MAGMA_HIDEOUT_1F, 99, MAP_MAGMA_HIDEOUT_1F, 0) \
    F(MAGMA_HIDEOUT_2F_1R, 100, MAP_MAGMA_HIDEOUT_2F_1R, 0) \
    F(MAGMA_HIDEOUT_2F_2R, 101, MAP_MAGMA_HIDEOUT_2F_2R, 0) \
    F(MAGMA_HIDEOUT_3F_1R, 102, MAP_MAGMA_HIDEOUT_3F_1R, 0) \
    F(MAGMA_HIDEOUT_3F_2R, 103, MAP_MAGMA_HIDEOUT_3F_2R, 0) \
    F(MAGMA_HIDEOUT_4F, 104, MAP_MAGMA_HIDEOUT_4F, 0) \
    F(MAGMA_HIDEOUT_3F_3R, 105, MAP_MAGMA_HIDEOUT_3F_3R, 0) \
    F(MAGMA_HIDEOUT_2F_3R, 106, MAP_MAGMA_HIDEOUT_2F_3R, 0) \
    F(MIRAGE_TOWER_1F, 107, MAP_MIRAGE_TOWER_1F, 0) \
    F(MIRAGE_TOWER_2F, 108, MAP_MIRAGE_TOWER_2F, 0) \
    F(MIRAGE_TOWER_3F, 109, MAP_MIRAGE_TOWER_3F, 0) \
    F(MIRAGE_TOWER_4F, 110, MAP_MIRAGE_TOWER_4F, 0) \
    F(DESERT_UNDERPASS, 111, MAP_DESERT_UNDERPASS, 0) \
    F(ARTISAN_CAVE_B1F, 112, MAP_ARTISAN_CAVE_B1F, 0) \
    F(ARTISAN_CAVE_1F, 113, MAP_ARTISAN_CAVE_1F, 0) \
    F(ALTERING_CAVE_1, 114, MAP_ALTERING_CAVE, 0) \
    F(ALTERING_CAVE_2, 115, MAP_ALTERING_CAVE, 1) \
    F(ALTERING_CAVE_3, 116, MAP_ALTERING_CAVE, 2) \
    F(ALTERING_CAVE_4, 117, MAP_ALTERING_CAVE, 3) \
    F(ALTERING_CAVE_5, 118, MAP_ALTERING_CAVE, 4) \
    F(ALTERING_CAVE_6, 119, MAP_ALTERING_CAVE, 5) \
    F(ALTERING_CAVE_7, 120, MAP_ALTERING_CAVE, 6) \
    F(ALTERING_CAVE_8, 121, MAP_ALTERING_CAVE, 7) \
    F(ALTERING_CAVE_9, 122, MAP_ALTERING_CAVE, 8) \
    F(METEOR_FALLS_STEVENS_CAVE, 123, MAP_METEOR_FALLS_STEVENS_CAVE, 0) \
    F(ROUTENEW101, 124, MAP_ROUTENEW101, 0) \
    F(LITTLEROOT_TOWN_2, 125, MAP_LITTLEROOT_TOWN_2, 0) \
    F(OLDALE_FIELD, 126, MAP_OLDALE_FIELD, 0) \
    F(OLDALE_TOWN_OLD_TUNEL, 127, MAP_OLDALE_TOWN_OLD_TUNEL, 0) \
    F(OLDALE_TOWN_OLD_TUNEL_2, 128, MAP_OLDALE_TOWN_OLD_TUNEL_2, 0) \
    F(RUSTBORO_CITY, 129, MAP_RUSTBORO_CITY, 0) \
    F(GRANITE_HILL, 130, MAP_GRANITE_HILL, 0) \
    F(LONELY_CAVE_B1, 131, MAP_LONELY_CAVE_B1, 0) \
    F(LONELY_CAVE_B2, 132, MAP_LONELY_CAVE_B2, 0) \
    F(LITTLEROOT_COAST, 133, MAP_LITTLEROOT_COAST, 0) \
    F(RUSTURF_GROVE, 134, MAP_RUSTURF_GROVE, 0) \
    F(RUINOUS_VALLEY, 135, MAP_RUINOUS_VALLEY, 0) \
    F(PETALBURG_WOODS_EAST, 136, MAP_PETALBURG_WOODS_EAST, 0) \
    F(MT_CHIMNEY, 137, MAP_MT_CHIMNEY, 0) \
    F(LITTLEROOT_TOWN, 138, MAP_LITTLEROOT_TOWN, 0) \
    F(VERDANTURF_TOWN, 139, MAP_VERDANTURF_TOWN, 0) \
    F(DEWDROP_JUNGLE, 140, MAP_DEWDROP_JUNGLE, 0) \
    F(PETALBURG_CAVE, 141, MAP_PETALBURG_CAVE, 0) \
    F(ROGUE_CANYON, 142, MAP_ROGUE_CANYON, 0) \
    F(LITTLEROOT_COAST2, 143, MAP_LITTLEROOT_COAST2, 0) \
    F(PETALBURG_CAVE_2, 145, MAP_PETALBURG_CAVE_2, 0) \
    F(FOSSIL_TRENCH, 146, MAP_FOSSIL_TRENCH, 0) \
    F(UNDERWATER_ROUTE131, 147, MAP_UNDERWATER_ROUTE131, 0) \
    F(AURORAGROVE, 148, MAP_AURORAGROVE, 0) \
    F(MAUVILLE_CITY, 149, MAP_MAUVILLE_CITY, 0) \
    F(MT_PYRE_CAVE, 150, MAP_MT_PYRE_CAVE, 0)

#define DEFINE_ENCOUNTER_ID(name, id, map, variant) ENCOUNTER_ID_##name = id,
enum HlwEncounterId
{
    HLW_ENCOUNTER_REGISTRY(DEFINE_ENCOUNTER_ID)
};
#undef DEFINE_ENCOUNTER_ID

#endif // GUARD_CONSTANTS_ENCOUNTER_IDS_H

