#ifndef GUARD_CONSTANTS_HIDDEN_GROTTO_H
#define GUARD_CONSTANTS_HIDDEN_GROTTO_H

#define HIDDEN_GROTTO_UNSET       0
#define HIDDEN_GROTTO_EMPTY       1
#define HIDDEN_GROTTO_POKEMON     2
#define HIDDEN_GROTTO_ITEM        3
#define HIDDEN_GROTTO_HIDDEN_ITEM 4

#define NUM_HIDDEN_GROTTOES 20

#endif // GUARD_CONSTANTS_HIDDEN_GROTTO_H
