#ifndef GUARD_MINING_CONSTANTS

#define GUARD_MINING_CONSTANTS


/*********** OTHER ************/
#define MINING_ITEM_TILE_NONE           0
#define MINING_ITEM_TILE_DUG_UP         5
#define MINING_MAX_NUM_BURIED_ITEMS     4
#define MINING_MAX_NUM_BURIED_STONES    2

#define MINING_WALL_SUCCESS_PERCENT     50
#define MINING_WALL_ATTEMPT_COUNT       80
#define FLAG_SYS_MINING_WALLS_UNLOCKED  FLAG_UNUSED_0x886
#define MINING_FREE_SESSIONS_PER_DAY   5
#define MINING_PAID_SESSION_COST       2000

enum
{
    MINING_WALL_RESULT_LOCKED,
    MINING_WALL_RESULT_ALREADY_TRIED,
    MINING_WALL_RESULT_CAN_MINE,
    MINING_WALL_RESULT_EMPTY,
    MINING_WALL_RESULT_NO_ENERGY,
};

enum MiningItemPool
{
    MINING_POOL_DEFAULT,
    MINING_POOL_JAGGED_PASS,
    MINING_POOL_GRANITE_CAVE,
    MINING_POOL_ROUTE_111,
    MINING_POOL_VICTORY_ROAD,
    MINING_POOL_MOSSDEEP_CAVE,
};

enum MiningLocation
{
    MINING_LOCATION_JAGGED_PASS,
    MINING_LOCATION_GRANITE_CAVE,
    MINING_LOCATION_ROUTE_111,
    MINING_LOCATION_VICTORY_ROAD,
    MINING_LOCATION_MOSSDEEP_CAVE,
    MINING_LOCATION_COUNT,
};

enum MiningSessionResult
{
    MINING_SESSION_RESULT_FREE,
    MINING_SESSION_RESULT_REQUIRES_PAYMENT,
};

/*********** SOUNDS ************/
#define MINING_SE_HIT_HAMMER            SE_M_ROCK_THROW
#define MINING_SE_HIT_PICKAXE           SE_M_DIG
#define MINING_SE_HIT_DUG_UP            SE_ICE_STAIRS
#define MINING_SE_WALL_COLLAPSE         SE_M_EARTHQUAKE
#define MINING_SE_TOOL_SWITCH           SE_ROTATING_GATE
#define MINING_SE_ITEM_SPARKLE          SE_RG_CARD_OPEN

/*********** ITEM SPRITE TAGS ************/
enum
{
    MINING_TAG_ITEM_HEARTSCALE = 12,
    MINING_TAG_ITEM_HARDSTONE,
    MINING_TAG_ITEM_REVIVE,
    MINING_TAG_ITEM_STAR_PIECE,
    MINING_TAG_ITEM_DAMP_ROCK,
    MINING_TAG_ITEM_RED_SHARD,
    MINING_TAG_ITEM_BLUE_SHARD,
    MINING_TAG_ITEM_IRON_BALL,
    MINING_TAG_ITEM_REVIVE_MAX,
    MINING_TAG_ITEM_EVER_STONE,
    MINING_TAG_ITEM_OVAL_STONE,
    MINING_TAG_ITEM_LIGHT_CLAY,
    MINING_TAG_ITEM_HEAT_ROCK,
    MINING_TAG_ITEM_ICY_ROCK,
    MINING_TAG_ITEM_SMOOTH_ROCK,
    MINING_TAG_ITEM_YELLOW_SHARD,
    MINING_TAG_ITEM_GREEN_SHARD,
    MINING_TAG_ITEM_LEAF_STONE,
    MINING_TAG_ITEM_FIRE_STONE,
    MINING_TAG_ITEM_WATER_STONE,
    MINING_TAG_ITEM_THUNDER_STONE,
    MINING_TAG_ITEM_MOON_STONE,
    MINING_TAG_ITEM_SUN_STONE,
    MINING_TAG_ITEM_HELIX_FOSSIL,
    MINING_TAG_ITEM_DOME_FOSSIL,
    MINING_TAG_ITEM_OLD_AMBER,
    MINING_TAG_ITEM_ROOT_FOSSIL,
    MINING_TAG_ITEM_CLAW_FOSSIL,

    MINING_TAG_STONE_1X4,
    MINING_TAG_STONE_4X1,
    MINING_TAG_STONE_2X4,
    MINING_TAG_STONE_4X2,
    MINING_TAG_STONE_2X2,
    MINING_TAG_STONE_3X3,
    MINING_TAG_STONE_SNAKE1,
    MINING_TAG_STONE_SNAKE2,
    MINING_TAG_STONE_MUSHROOM1,
    MINING_TAG_STONE_MUSHROOM2,
    MINING_TAG_ITEM_DUSK_STONE,
    MINING_TAG_ITEM_SHINY_STONE,
    MINING_TAG_ITEM_PRISM_SCALE,
    MINING_TAG_ITEM_KINGS_ROCK,
    MINING_TAG_ITEM_BIG_NUGGET,
    MINING_TAG_ITEM_ICE_STONE,
    MINING_TAG_ITEM_DAWN_STONE,
    MINING_TAG_ITEM_RARE_BONE,
    MINING_TAG_ITEM_BIG_PEARL,
    MINING_TAG_ITEM_COMET_SHARD,
};

/*********** FLAGS ************/
#define MINING_FLAG_USE_DEFAULT_MESSAGE_BOX            FALSE

enum
{
    MININGID_NONE,
    MININGID_STONE_1x4,
    MININGID_STONE_4x1,
    MININGID_STONE_2x4,
    MININGID_STONE_4x2,
    MININGID_STONE_2x2,
    MININGID_STONE_3x3,
    MININGID_STONE_SNAKE1,
    MININGID_STONE_SNAKE2,
    MININGID_STONE_MUSHROOM1,
    MININGID_STONE_MUSHROOM2,
    MININGID_HEART_SCALE,
    MININGID_HARD_STONE,
    MININGID_REVIVE,
    MININGID_STAR_PIECE,
    MININGID_DAMP_ROCK,
    MININGID_RED_SHARD,
    MININGID_BLUE_SHARD,
    MININGID_IRON_BALL,
    MININGID_REVIVE_MAX,
    MININGID_EVER_STONE,
    MININGID_OVAL_STONE,
    MININGID_LIGHT_CLAY,
    MININGID_HEAT_ROCK,
    MININGID_ICY_ROCK,
    MININGID_SMOOTH_ROCK,
    MININGID_YELLOW_SHARD,
    MININGID_GREEN_SHARD,
    MININGID_LEAF_STONE,
    MININGID_FIRE_STONE,
    MININGID_WATER_STONE,
    MININGID_THUNDER_STONE,
    MININGID_MOON_STONE,
    MININGID_SUN_STONE,
    MININGID_HELIX_FOSSIL,
    MININGID_DOME_FOSSIL,
    MININGID_OLD_AMBER,
    MININGID_ROOT_FOSSIL,
    MININGID_CLAW_FOSSIL,
    MININGID_DUSK_STONE,
    MININGID_SHINY_STONE,
    MININGID_PRISM_SCALE,
    MININGID_KINGS_ROCK,
    MININGID_BIG_NUGGET,
    MININGID_ICE_STONE,
    MININGID_DAWN_STONE,
    MININGID_RARE_BONE,
    MININGID_BIG_PEARL,
    MININGID_COMET_SHARD,
};

#define MINING_COUNT_ID_STONE           MININGID_STONE_MUSHROOM2

#define MINING_ZONE_WIDTH 12
#define MINING_ZONE_HEIGHT 8

#define MINING_ZONE_1_X_LEFT_BOUNDARY     0
#define MINING_ZONE_1_X_RIGHT_BOUNDARY    5
#define MINING_ZONE_1_Y_UP_BOUNDARY       0
#define MINING_ZONE_1_Y_DOWN_BOUNDARY     3

#define MINING_ZONE_2_X_LEFT_BOUNDARY     0
#define MINING_ZONE_2_X_RIGHT_BOUNDARY    5
#define MINING_ZONE_2_Y_UP_BOUNDARY       4
#define MINING_ZONE_2_Y_DOWN_BOUNDARY     MINING_ZONE_HEIGHT - 1;

#define MINING_ZONE_3_X_LEFT_BOUNDARY     6
#define MINING_ZONE_3_X_RIGHT_BOUNDARY    MINING_ZONE_WIDTH - 1
#define MINING_ZONE_3_Y_UP_BOUNDARY       0
#define MINING_ZONE_3_Y_DOWN_BOUNDARY     3

#define MINING_ZONE_4_X_LEFT_BOUNDARY     6
#define MINING_ZONE_4_X_RIGHT_BOUNDARY    MINING_ZONE_WIDTH - 1
#define MINING_ZONE_4_Y_UP_BOUNDARY       4
#define MINING_ZONE_4_Y_DOWN_BOUNDARY     MINING_ZONE_HEIGHT - 1

/*********** DEBUG FLAGS ************/
#define MINING_DEBUG_ENABLE                                 FALSE

#if MINING_DEBUG_ENABLE == TRUE
    #define MINING_DEBUG_ALL_SPRITES_VISIBLE                TRUE
    #define MINING_DEBUG_INFINITE_HITS                      FALSE
    #define MINING_DEBUG_ENABLE_ITEM_GENERATION_OPTIONS     TRUE
    #define MINING_DEBUG_ENABLE_STONE_GENERATION_OPTIONS    FALSE

    #if MINING_DEBUG_ENABLE_ITEM_GENERATION_OPTIONS == TRUE
        #define MINING_DEBUG_DESIRED_NUMBER_OF_ITEMS   2
        #define MINING_DEBUG_MININGID_ITEM1            MININGID_LEAF_STONE
        #define MINING_DEBUG_MININGID_ITEM2            MININGID_THUNDER_STONE
        #define MINING_DEBUG_MININGID_ITEM3            MININGID_THUNDER_STONE
        #define MINING_DEBUG_MININGID_ITEM4            MININGID_SUN_STONE
    #endif

    #if MINING_DEBUG_ENABLE_STONE_GENERATION_OPTIONS == TRUE
        #define MINING_DEBUG_MININGID_STONE1           MININGID_STONE_MUSHROOM1
        #define MINING_DEBUG_MININGID_STONE2           MININGID_STONE_MUSHROOM2
    #endif
#endif

#endif
