#ifndef GUARD_CONSTANTS_PAINTINGS_H
#define GUARD_CONSTANTS_PAINTINGS_H

#define PAINTING_1  0
#define PAINTING_2  1
#define PAINTING_3  2
#define PAINTING_COUNT 3

#endif // GUARD_CONSTANTS_PAINTINGS_H
