voice_group guts_theme
    voice_keysplit voicegroup_piano_keysplit, keysplit_piano @ 0 - HLW piano
    voice_directsound 60, 0, DirectSoundWaveData_sc88pro_string_ensemble_72, 255, 0, 240, 180 @ 1 - HLW violin
    voice_directsound 60, 0, DirectSoundWaveData_classical_choir_voice_ahhs, 210, 0, 245, 210 @ 2 - HLW REAL CHOIR AAH
    voice_directsound 60, 0, DirectSoundWaveData_unknown_female_voice, 220, 0, 240, 210 @ 3 - HLW FEMALE OOH SUPPORT
