Route110House_MapScripts::
    .byte 0

Route110House_EventScript_OldWoman::
    msgbox Route110House_Text_BridgeIsRoundabout, MSGBOX_NPC
    end

Route110House_Text_BridgeIsRoundabout:
    .string "Why did we ever move to such a place?\n"
    .string "What an inconvenient place to live.$"

Route110House_EventScript_OldMan::
    msgbox Route110House_Text_BikersCutDownTrees, MSGBOX_NPC
    end

Route110House_Text_BikersCutDownTrees:
    .string "If cycling road is as great\n"
    .string "as they say, why do so many noisy\l"
    .string "trainers still come by this way?\p"
    .string "I planted trees to keep them out,\n"
    .string "but they just cut them down!$"
