gText_Birch_Welcome::
.string "The world has collapsed...\p"
.string "Hoenn isn't the same anymore...\p"
.string "I am CELEBI, the Time Travel POKéMON.\p"
.string "I've traveled from Johto to Hoenn...\n"
.string "to find JIRACHI, the wish-granting...\p"
.string "But we cannot save Hoenn alone...\p"
.string "$"

gText_Birch_Pokemon:: @ useless text, never used in the game
	.string "But we cannot save Hoenn alone...”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Have you heard the legends of HIM?\n"
	.string "Known as the Sky High POKéMON.\p"
	.string "He lives in the ozone layer, feeding on\n"
	.string "meteoroids, only descending to Earth\l"
	.string "to stop the clashes between...\p"
	.string "KYOGRE and GROUDON...\n"
	.string "Him... The Dragon God POKéMON:\p"
	.string "RAYQUAZA...\n"
	.string "For centuries he ruled the sky...\p"
	.string "Supreme enough to appease a primordial\n"
	.string "elemental battle between the ruler\p"
	.string "of the sea and the creator of the land.\n"
	.string "Unfortunately evil human interference\l"
	.string "broke this perfect balance forever...\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And tell us, YOU are?$"

gText_Birch_BoyOrGirl::
	.string "Are YOU a boy?\n"
	.string "Or are YOU a girl?$"

gText_Birch_WhatsYourName::
	.string "You were chosen by destiny...\n"
	.string "What was your name again?$"

gText_Birch_SoItsPlayer::
	.string "Yes, we already knew your name...\p"
	.string "{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
    .string "CELEBI: Perfect...\p"
    .string "Trust me, everything will be fine.\p"
    .string "This is, in truth, a dream...\n"
    .string "A special connection we share.\p"
    .string "We need your help to save Hoenn\n"
    .string "from a cruel fate born of greed...\p"
    .string "$"

gText_Birch_AreYouReady::
    .string "Don't be afraid, {PLAYER}.\p"
    .string "The DREAM WORLD may feel strange at\n"
    .string "first… but you're not alone.\p"
    .string "We’re here to guide you.\n"
    .string "Just breathe… and trust us.\p"
    .string "Step forward and follow the path that\n"
    .string "fate has chosen for you...\p"
	.string "$"


	


