#ifndef GUARD_CONFIG_RANDOMIZER_H
#define GUARD_CONFIG_RANDOMIZER_H

#define RANDOMIZER_AVAILABLE TRUE

#define RANDOMIZER_FLAG_WILD_MON        FLAG_RANDOMIZER_WILD
#define RANDOMIZER_FLAG_TRAINER_MON     FLAG_RANDOMIZER_TRAINER
#define RANDOMIZER_VAR_SPECIES_MODE     VAR_RANDOMIZER_MODE   
#define RANDOMIZER_VAR_SEED_L           VAR_RANDOMIZER_SEED_L   
#define RANDOMIZER_VAR_SEED_H           VAR_RANDOMIZER_SEED_H 

#define RANDOMIZER_SEED_FROM_TRAINER_ID TRUE
#define RANDOMIZER_EXCLUDE_LEGENDS_FROM_COMMON TRUE
#define RANDOMIZER_ALLOW_REGIONAL_FORMS FALSE
#define RANDOMIZER_BST_TOLERANCE 30

// Starter minimum BST (250 exclude Caterpie, Magikarp, etc.)
#ifndef RANDOMIZER_STARTER_MIN_BST
#define RANDOMIZER_STARTER_MIN_BST 250
#endif

#endif
