# 1 "data/maps/PHOENIXHOUSE2/scripts.pory"

# 2 "data/maps/PHOENIXHOUSE2/scripts.pory"
PHOENIXHOUSE2_MapScripts::
# 3 "data/maps/PHOENIXHOUSE2/scripts.pory"
	.byte 0
# 4 "data/maps/PHOENIXHOUSE2/scripts.pory"

# 5 "data/maps/PHOENIXHOUSE2/scripts.pory"
PHOENIXHOUSE2_EventScript_Woman::
# 6 "data/maps/PHOENIXHOUSE2/scripts.pory"
	msgbox PHOENIXHOUSE2_Text_SlowLife, MSGBOX_NPC
# 7 "data/maps/PHOENIXHOUSE2/scripts.pory"
	end
# 8 "data/maps/PHOENIXHOUSE2/scripts.pory"

# 9 "data/maps/PHOENIXHOUSE2/scripts.pory"
PHOENIXHOUSE2_Text_SlowLife:
# 10 "data/maps/PHOENIXHOUSE2/scripts.pory"
	.string "Life is slow here.\p"
# 11 "data/maps/PHOENIXHOUSE2/scripts.pory"
	.string "We learn to listen before\n"
# 12 "data/maps/PHOENIXHOUSE2/scripts.pory"
	.string "the ground moves.$"
