# 1 "data/maps/OldaleTown_House1/scripts.pory"

# 2 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_MapScripts::
# 3 "data/maps/OldaleTown_House1/scripts.pory"
	.byte 0
# 4 "data/maps/OldaleTown_House1/scripts.pory"

# 5 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_EventScript_Woman::
# 6 "data/maps/OldaleTown_House1/scripts.pory"
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
# 7 "data/maps/OldaleTown_House1/scripts.pory"
	end
# 8 "data/maps/OldaleTown_House1/scripts.pory"

# 9 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_Text_LeftPokemonGoesOutFirst:
# 10 "data/maps/OldaleTown_House1/scripts.pory"
    .string "Whoa, you have a POKéMON?\n"
# 11 "data/maps/OldaleTown_House1/scripts.pory"
    .string "That is so cute!\p"
# 12 "data/maps/OldaleTown_House1/scripts.pory"
    .string "I always dreamed of having one and\n"
# 13 "data/maps/OldaleTown_House1/scripts.pory"
    .string "becoming a TRAINER myself.\p"
# 14 "data/maps/OldaleTown_House1/scripts.pory"
    .string "I think I might go check the OLD TUNNEL\n"
# 15 "data/maps/OldaleTown_House1/scripts.pory"
    .string "east of town to find a POKéMON of my own.\p"
# 16 "data/maps/OldaleTown_House1/scripts.pory"
    .string "I'm so jealous!$"
