voice_group get_lucky_drumset, 31
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 255, 127 @ 31
	.rept 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_rnd_kick, 255, 0, 255, 0 @ 35
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_sc88pro_rnd_snare, 255, 0, 255, 0 @ 37
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 60, 64, DirectSoundWaveData_sc88pro_tr909_hand_clap, 255, 0, 255, 242 @ 39
	voice_directsound_no_resample 64, 64, DirectSoundWaveData_unknown_synth_snare, 255, 0, 255, 0 @ 40
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_close_hihat, 255, 0, 255, 0 @ 42
	.rept 3
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound_no_resample 60, 79, DirectSoundWaveData_unknown_open_hihat, 255, 0, 255, 0 @ 46
	.rept 2
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0
	.endr
	voice_directsound_no_resample 30, 54, DirectSoundWaveData_sc88pro_orchestra_cymbal_crash, 255, 0, 255, 234 @ 49
