# 1 "data/maps/SlateportCity_House/scripts.pory"

# 2 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_MapScripts::
# 3 "data/maps/SlateportCity_House/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_House/scripts.pory"

# 5 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_PokefanM::
# 6 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
# 7 "data/maps/SlateportCity_House/scripts.pory"
	end
# 8 "data/maps/SlateportCity_House/scripts.pory"

# 9 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_Girl::
# 10 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
# 11 "data/maps/SlateportCity_House/scripts.pory"
	end
# 12 "data/maps/SlateportCity_House/scripts.pory"

# 13 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_NatureToDoWithStatGains:
# 14 "data/maps/SlateportCity_House/scripts.pory"
	.string "They say Slateport grew from nothing\n"
# 15 "data/maps/SlateportCity_House/scripts.pory"
	.string "but clean water and abundant food.\p"
# 16 "data/maps/SlateportCity_House/scripts.pory"
	.string "Now ships and people from all\n"
# 17 "data/maps/SlateportCity_House/scripts.pory"
	.string "over Hoenn come here to trade.\p"
# 18 "data/maps/SlateportCity_House/scripts.pory"
	.string "Since SEABREEZE SHIPPING got set up\n"
# 19 "data/maps/SlateportCity_House/scripts.pory"
	.string "here, we have even started seeing\l"
# 20 "data/maps/SlateportCity_House/scripts.pory"
	.string "goods from other regions!$"
# 21 "data/maps/SlateportCity_House/scripts.pory"

# 22 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_MustBeGoingToBattleTent:
# 23 "data/maps/SlateportCity_House/scripts.pory"
	.string "Welcome to Slateport City.\n"
# 24 "data/maps/SlateportCity_House/scripts.pory"
	.string "This place is where people and\l"
# 25 "data/maps/SlateportCity_House/scripts.pory"
	.string "POKéMON cross paths with nature.\p"
# 26 "data/maps/SlateportCity_House/scripts.pory"
	.string "A market grew from clean water,\n"
# 27 "data/maps/SlateportCity_House/scripts.pory"
	.string "and a lighthouse guards the bay.\p"
# 28 "data/maps/SlateportCity_House/scripts.pory"
	.string "It's only natural for such a thriving\n"
# 29 "data/maps/SlateportCity_House/scripts.pory"
	.string "city to rise from a shipping hub.$"
