RustboroCity_Flat2_3F_MapScripts::
	.byte 0

RustboroCity_Flat2_3F_EventScript_DevonEmployee::
	msgbox RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones, MSGBOX_NPC
	end

RustboroCity_Flat2_3F_EventScript_Woman::
	msgbox RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones, MSGBOX_NPC
	end

RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones:
	.string "PORYGON is fascinating, a POKéMON made\n"
	.string "entirely of binary computer code!\p"
	.string "It can digitize itself and explore\n"
	.string "cyberspace. I'ts so amazing!\p"
	.string "But PORYGON2 and PORYGON Z? Their\n"
	.string "behavior is… kinda wierd, honestly.$"

RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones:
	.string "My boyfriend's a computer genius at\n"
	.string "DEVON. He programs PORYGON!\p"
	.string "But honestly? He's such a nerd. Always\n"
	.string "mumbling about computers and data…\p"
	.string "I just want to go on an exciting\n"
	.string "adventure for once! Right?$"

