# 1 "data/maps/SlateportCity_House2/scripts.pory"

# 2 "data/maps/SlateportCity_House2/scripts.pory"
SlateportCity_House2_MapScripts::
# 3 "data/maps/SlateportCity_House2/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_House2/scripts.pory"

# 5 "data/maps/SlateportCity_House2/scripts.pory"
SlateportCity_House2_EventScript_Lass::
# 6 "data/maps/SlateportCity_House2/scripts.pory"
	msgbox SlateportCity_House2_Text_Placeholder, MSGBOX_NPC
# 7 "data/maps/SlateportCity_House2/scripts.pory"
	end
# 8 "data/maps/SlateportCity_House2/scripts.pory"

# 9 "data/maps/SlateportCity_House2/scripts.pory"
SlateportCity_House2_Text_Placeholder:
# 10 "data/maps/SlateportCity_House2/scripts.pory"
	.string "My dad works on one of the cargo\n"
# 11 "data/maps/SlateportCity_House2/scripts.pory"
	.string "ships that docks in town.\p"
# 12 "data/maps/SlateportCity_House2/scripts.pory"
	.string "He has such a cool job!\n"
# 13 "data/maps/SlateportCity_House2/scripts.pory"
	.string "I do miss him sometimes though...$"
