# 1 "data/maps/OldaleField/scripts.pory"

# 2 "data/maps/OldaleField/scripts.pory"
OldaleField_MapScripts::
# 3 "data/maps/OldaleField/scripts.pory"
	.byte 0
# 4 "data/maps/OldaleField/scripts.pory"

# 5 "data/maps/OldaleField/scripts.pory"

# 6 "data/maps/OldaleField/scripts.pory"
OldaleFieldAbraMan::
# 7 "data/maps/OldaleField/scripts.pory"
# 4 "data/maps/OldaleField/scripts.pory"
# 8 "data/maps/OldaleField/scripts.pory"
	lock
# 9 "data/maps/OldaleField/scripts.pory"
# 5 "data/maps/OldaleField/scripts.pory"
# 10 "data/maps/OldaleField/scripts.pory"
	faceplayer
# 11 "data/maps/OldaleField/scripts.pory"
# 6 "data/maps/OldaleField/scripts.pory"
# 12 "data/maps/OldaleField/scripts.pory"
	msgbox OldaleFieldAbraManDialogue, MSGBOX_NPC
# 13 "data/maps/OldaleField/scripts.pory"
# 7 "data/maps/OldaleField/scripts.pory"
# 14 "data/maps/OldaleField/scripts.pory"
	release
# 15 "data/maps/OldaleField/scripts.pory"
	end
# 16 "data/maps/OldaleField/scripts.pory"

# 17 "data/maps/OldaleField/scripts.pory"

# 18 "data/maps/OldaleField/scripts.pory"
OldaleFieldGirl::
# 19 "data/maps/OldaleField/scripts.pory"
# 12 "data/maps/OldaleField/scripts.pory"
# 20 "data/maps/OldaleField/scripts.pory"
	lock
# 21 "data/maps/OldaleField/scripts.pory"
# 13 "data/maps/OldaleField/scripts.pory"
# 22 "data/maps/OldaleField/scripts.pory"
	faceplayer
# 23 "data/maps/OldaleField/scripts.pory"
# 14 "data/maps/OldaleField/scripts.pory"
# 24 "data/maps/OldaleField/scripts.pory"
	msgbox OldaleFieldGirlDialogue, MSGBOX_NPC
# 25 "data/maps/OldaleField/scripts.pory"
# 15 "data/maps/OldaleField/scripts.pory"
# 26 "data/maps/OldaleField/scripts.pory"
	release
# 27 "data/maps/OldaleField/scripts.pory"
	end
# 28 "data/maps/OldaleField/scripts.pory"

# 29 "data/maps/OldaleField/scripts.pory"

# 30 "data/maps/OldaleField/scripts.pory"
SentretOverworld::
# 31 "data/maps/OldaleField/scripts.pory"
# 20 "data/maps/OldaleField/scripts.pory"
# 32 "data/maps/OldaleField/scripts.pory"
	lock
# 33 "data/maps/OldaleField/scripts.pory"
# 21 "data/maps/OldaleField/scripts.pory"
# 34 "data/maps/OldaleField/scripts.pory"
	faceplayer
# 35 "data/maps/OldaleField/scripts.pory"
# 22 "data/maps/OldaleField/scripts.pory"
# 36 "data/maps/OldaleField/scripts.pory"
	playmoncry SPECIES_SENTRET, CRY_MODE_NORMAL
# 37 "data/maps/OldaleField/scripts.pory"
# 23 "data/maps/OldaleField/scripts.pory"
# 38 "data/maps/OldaleField/scripts.pory"
	waitmoncry
# 39 "data/maps/OldaleField/scripts.pory"
# 24 "data/maps/OldaleField/scripts.pory"
# 40 "data/maps/OldaleField/scripts.pory"
	release
# 41 "data/maps/OldaleField/scripts.pory"
	end
# 42 "data/maps/OldaleField/scripts.pory"

# 43 "data/maps/OldaleField/scripts.pory"

# 44 "data/maps/OldaleField/scripts.pory"
AbraOverworld::
# 45 "data/maps/OldaleField/scripts.pory"
# 29 "data/maps/OldaleField/scripts.pory"
# 46 "data/maps/OldaleField/scripts.pory"
	lock
# 47 "data/maps/OldaleField/scripts.pory"
# 30 "data/maps/OldaleField/scripts.pory"
# 48 "data/maps/OldaleField/scripts.pory"
	faceplayer
# 49 "data/maps/OldaleField/scripts.pory"
# 31 "data/maps/OldaleField/scripts.pory"
# 50 "data/maps/OldaleField/scripts.pory"
	playmoncry SPECIES_ABRA, CRY_MODE_NORMAL
# 51 "data/maps/OldaleField/scripts.pory"
# 32 "data/maps/OldaleField/scripts.pory"
# 52 "data/maps/OldaleField/scripts.pory"
	waitmoncry
# 53 "data/maps/OldaleField/scripts.pory"
# 33 "data/maps/OldaleField/scripts.pory"
# 54 "data/maps/OldaleField/scripts.pory"
	release
# 55 "data/maps/OldaleField/scripts.pory"
	end
# 56 "data/maps/OldaleField/scripts.pory"

# 57 "data/maps/OldaleField/scripts.pory"

# 58 "data/maps/OldaleField/scripts.pory"
OldTunnelSign::
# 59 "data/maps/OldaleField/scripts.pory"
# 38 "data/maps/OldaleField/scripts.pory"
# 60 "data/maps/OldaleField/scripts.pory"
	lock
# 61 "data/maps/OldaleField/scripts.pory"
# 39 "data/maps/OldaleField/scripts.pory"
# 62 "data/maps/OldaleField/scripts.pory"
	faceplayer
# 63 "data/maps/OldaleField/scripts.pory"
# 40 "data/maps/OldaleField/scripts.pory"
# 64 "data/maps/OldaleField/scripts.pory"
	msgbox OldTunnelSign_Text_0, MSGBOX_SIGN
# 65 "data/maps/OldaleField/scripts.pory"
# 41 "data/maps/OldaleField/scripts.pory"
# 66 "data/maps/OldaleField/scripts.pory"
	release
# 67 "data/maps/OldaleField/scripts.pory"
	end
# 68 "data/maps/OldaleField/scripts.pory"

# 69 "data/maps/OldaleField/scripts.pory"

# 70 "data/maps/OldaleField/scripts.pory"
OldTunnelSign_Text_0:
# 71 "data/maps/OldaleField/scripts.pory"
# 40 "data/maps/OldaleField/scripts.pory"
# 72 "data/maps/OldaleField/scripts.pory"
	.string "OLD TUNNEL$"
# 73 "data/maps/OldaleField/scripts.pory"

# 74 "data/maps/OldaleField/scripts.pory"
OldaleFieldAbraManDialogue::
# 75 "data/maps/OldaleField/scripts.pory"
# 45 "data/maps/OldaleField/scripts.pory"
# 76 "data/maps/OldaleField/scripts.pory"
	.string "I explored this dark cave to the\n"
# 77 "data/maps/OldaleField/scripts.pory"
	.string "fullest in seach of rare POKéMON!\p"
# 78 "data/maps/OldaleField/scripts.pory"
	.string "I found this Abra, which doesn't even\n"
# 79 "data/maps/OldaleField/scripts.pory"
	.string "have an attack. What am I going to do\l"
# 80 "data/maps/OldaleField/scripts.pory"
	.string "with this now?$"
# 81 "data/maps/OldaleField/scripts.pory"

# 82 "data/maps/OldaleField/scripts.pory"
OldaleFieldGirlDialogue::
# 83 "data/maps/OldaleField/scripts.pory"
# 52 "data/maps/OldaleField/scripts.pory"
# 84 "data/maps/OldaleField/scripts.pory"
	.string "Beware of those Sentret!\n"
# 85 "data/maps/OldaleField/scripts.pory"
	.string "They are so cute! I know...\p"
# 86 "data/maps/OldaleField/scripts.pory"
	.string "But they are stressed and energetic.\n"
# 87 "data/maps/OldaleField/scripts.pory"
	.string "They're always starting fights!$"
