Route115_lonely_cave_MapScripts::
	.byte 0


LonelyCave1F_Hiker::
# 4 "data/maps/Route115_lonely_cave/scripts.pory"
	lock
# 5 "data/maps/Route115_lonely_cave/scripts.pory"
	faceplayer
# 6 "data/maps/Route115_lonely_cave/scripts.pory"
	msgbox LonelyCave1F_Hiker_Text_0
# 7 "data/maps/Route115_lonely_cave/scripts.pory"
	release
	end


LonelyCave1F_Hiker_Text_0:
# 6 "data/maps/Route115_lonely_cave/scripts.pory"
	.string "The bottom floor of this place is quite\n"
	.string "eerie!$"
