# 1 "data/maps/PHOENIXHOUSE3/scripts.pory"

# 2 "data/maps/PHOENIXHOUSE3/scripts.pory"
PHOENIXHOUSE3_MapScripts::
# 3 "data/maps/PHOENIXHOUSE3/scripts.pory"
	.byte 0
# 4 "data/maps/PHOENIXHOUSE3/scripts.pory"

# 5 "data/maps/PHOENIXHOUSE3/scripts.pory"
PHOENIXHOUSE3_EventScript_ExpertM::
# 6 "data/maps/PHOENIXHOUSE3/scripts.pory"
	msgbox PHOENIXHOUSE3_Text_WarmStones, MSGBOX_NPC
# 7 "data/maps/PHOENIXHOUSE3/scripts.pory"
	end
# 8 "data/maps/PHOENIXHOUSE3/scripts.pory"

# 9 "data/maps/PHOENIXHOUSE3/scripts.pory"
PHOENIXHOUSE3_Text_WarmStones:
# 10 "data/maps/PHOENIXHOUSE3/scripts.pory"
	.string "Some stones from the first\n"
# 11 "data/maps/PHOENIXHOUSE3/scripts.pory"
	.string "quake stay warm in winter.\p"
# 12 "data/maps/PHOENIXHOUSE3/scripts.pory"
	.string "Nobody knows why.$"
