gText_Birch_Welcome::
.string "The world has collapsed…\p"
.string "HOENN has forever changed…\p"
.string "I am CELEBI, the Time Travel POKéMON.\p"
.string "I've journeyed from JOHTO to HOENN\n"
.string "to find JIRACHI, the wish-granter…\p"
.string "But we cannot save HOENN alone…\p"
.string "$"

gText_Birch_Pokemon:: @ useless text, never used in the game
	.string "But we cannot save HOENN alone…”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "Have you heard the legends?\p"
	.string "Of the one known as the Sky High\n"
	.string "POKéMON.\p"
	.string "He lives in the ozone layer, feeding on\n"
	.string "meteoroids…\p"
	.string "Only descending to Earth to stop the\n"
	.string "clashes between KYOGRE and GROUDON…\p"
	.string "He's the Dragon God POKéMON:\n"
	.string "RAYQUAZA…\p"
	.string "For centuries he ruled the sky…\p"
	.string "Powerful enough to stop battles\n"
	.string "between the Ruler of the Seas\l"
	.string "and the Creator of the Land.\p"
	.string "Unfortunately, human influence\n"
	.string "has broken this perfect balance…\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But tell us, who ARE you?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "You who were chosen by destiny…\n"
	.string "What is your name?$"

gText_Birch_SoItsPlayer::
	.string "Of course, we already knew your name…\p"
	.string "{PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
    .string "CELEBI: Perfect…\p"
    .string "Trust me, everything will be fine.\p"
    .string "This is, in truth, a dream…\n"
    .string "A special connection we share.\p"
    .string "We need your help to save HOENN from\n"
    .string "a cruel fate born of greed…\p"
    .string "$"

gText_Birch_AreYouReady::
    .string "Don't be afraid, {PLAYER}.\p"
    .string "The DREAM WORLD may feel strange at\n"
    .string "first… But you're not alone.\p"
    .string "We’re here to guide you.\n"
    .string "Just breathe… And trust us.\p"
    .string "Step forward and follow the path\n"
    .string "that fate has chosen for you…\p"
	.string "$"


	
